### PR TITLE
Fix syntax error

### PR DESCRIPTION
**Pull request by mchirino89**
Replaced uint32 by UInt32 in order to make the code compile again.

### CODE REVIEW

**Comment by mchirino89** [comment]
@idrougge Check it out, I think you'd find this little contribution useful

**Comment by idrougge** [comment]
Thank you!
Could this be some undocumented difference between Apple and Linux environments? I've been able to use `uint32` in place of `UInt32` since the first Swift 2 version.

**Review by idrougge — APPROVED** [review]
Nice and clean 👍

**Comment by mchirino89** [comment]
I guess so. Swift 4 introduced many dumb changes like that, I had to update several of my projects for small syntax errors like these.

**Pull request merged**
